Repository tokens-studio/graph-engine, pull requests merged in 2024-06, with the labels that each got.

#255 Fix subgraphs value issue
  packages/graph-editor/src/components/panels/dropPanel/data.tsx
  packages/graph-editor/src/components/panels/dropPanel/dropPanel.tsx
  packages/graph-editor/src/components/panels/inputs/dynamicInputs.tsx
  packages/graph-editor/src/editor/graph.tsx
  packages/graph-editor/src/registry/inputControls.tsx
  packages/graph-engine/src/nodes/generic/subgraph.ts
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#258 Reorder variadic ports
  packages/graph-editor/package.json
  packages/graph-editor/src/components/DndList.tsx
  packages/graph-editor/src/components/controls/index.tsx
  packages/graph-editor/src/components/controls/numeric.tsx
  packages/graph-editor/src/components/controls/variadicAny.tsx
  packages/graph-editor/src/components/controls/variadicColor.tsx
  packages/graph-editor/src/components/controls/variadicNumber.tsx
  packages/graph-editor/src/components/controls/withVariadicField.tsx
  packages/graph-editor/src/components/index.ts
  packages/graph-editor/src/components/menubar/defaults.tsx
  packages/graph-editor/src/components/panels/dropPanel/dropPanel.tsx
  packages/graph-editor/src/components/portPanel/index.tsx
  packages/graph-editor/src/editor/graph.tsx
  packages/graph-editor/src/registry/control.tsx
  packages/graph-editor/src/registry/icon.tsx
  packages/graph-editor/src/tokens/colors.ts
  packages/graph-engine/src/graph/graph.ts
  packages/graph-engine/src/nodes/array/arrify.ts
  packages/graph-engine/src/nodes/generic/objectMerge.ts
  packages/graph-engine/src/nodes/generic/subgraph.ts
  packages/graph-engine/src/nodes/logic/and.ts
  packages/graph-engine/src/nodes/logic/or.ts
  packages/graph-engine/src/nodes/math/addVariadic.ts
  packages/graph-engine/src/nodes/math/divideVariadic.ts
  packages/graph-engine/src/nodes/math/multiplyVariadic.ts
  packages/graph-engine/src/nodes/math/subtractVariadic.ts
  packages/graph-engine/src/schemas/index.ts
  packages/nodes-design-tokens/src/nodes/advancedBlend.ts
  packages/nodes-design-tokens/src/nodes/flatten.ts
  packages/nodes-design-tokens/src/schemas/index.ts
  packages/nodes-design-tokens/src/ui/controls/index.tsx
  packages/nodes-design-tokens/src/ui/controls/token.tsx
  packages/nodes-design-tokens/src/ui/controls/tokenSet.tsx
  packages/nodes-design-tokens/src/ui/controls/variadicTokenSet.tsx
  packages/nodes-design-tokens/src/ui/index.tsx
  yarn.lock
Labels: enhancement, Bug fix, Review effort [1-5]: 4, Dependencies

#261 fix color wheel
  .changeset/seven-items-dance.md
  packages/graph-engine/src/nodes/color/wheel.ts
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#263 fix valid check
  packages/graph-editor/src/hooks/useIsValidConnection.ts
Labels: Bug fix, Review effort [1-5]: 2

#259 Feat/debugger
  package.json
  packages/documentation/docs/guides/developers/engine/creating-a-node.md
  packages/graph-editor/package.json
  packages/graph-editor/src/components/debugger/data.ts
  packages/graph-editor/src/components/debugger/debugger.css
  packages/graph-editor/src/components/debugger/debugger.scss
  packages/graph-editor/src/components/debugger/index.stories.tsx
  packages/graph-editor/src/components/debugger/index.tsx
  packages/graph-editor/src/components/debugger/player.tsx
  packages/graph-editor/src/components/menubar/defaults.tsx
  packages/graph-editor/src/components/panels/debugger/index.tsx
  packages/graph-editor/src/components/panels/flamegraph/index.tsx
  packages/graph-editor/src/components/panels/flamegraph/story.stories.tsx
  packages/graph-editor/src/components/panels/flamegraph/utils.tsx
  packages/graph-editor/src/editor/graph.tsx
  packages/graph-editor/src/editor/layoutController.tsx
  packages/graph-editor/src/registry/inputControls.tsx
  packages/graph-engine/src/graph/graph.ts
  packages/graph-engine/src/nodes/array/reduce.ts
  packages/graph-engine/src/nodes/css/cssFunction.ts
  packages/graph-engine/src/programmatic/node.ts
  packages/graph-engine/src/types.ts
  packages/storybook-lit/package.json
  packages/storybook-react/package.json
  patches/react-virtualized+9.22.5.patch
  yarn.lock
Labels: enhancement, Review effort [1-5]: 4

#265 Fix flatten node
  packages/graph-editor/src/hooks/useIsValidConnection.ts
  packages/nodes-design-tokens/src/nodes/flatten.ts
  packages/nodes-design-tokens/src/ui/controls/index.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#264 add xyz65 to color convert
  packages/graph-engine/src/nodes/color/convert.ts
Labels: enhancement, Review effort [1-5]: 2

#268 add flatten alpha node
  .changeset/eleven-snakes-breathe.md
  packages/graph-engine/src/nodes/color/flattenAlpha.ts
  packages/graph-engine/src/nodes/color/index.ts
  packages/graph-engine/src/types.ts
Labels: enhancement, Review effort [1-5]: 3

#267 fix(1013): Subgraph output
  packages/graph-editor/src/components/flow/wrapper/nodeV2.tsx
  packages/graph-engine/src/nodes/generic/subgraph.ts
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#274 fix(273): Fix input output execution
  packages/graph-editor/src/components/flow/wrapper/nodeV2.tsx
  packages/graph-engine/src/nodes/generic/input.ts
  packages/graph-engine/src/nodes/generic/output.ts
  packages/graph-engine/src/programmatic/node.ts
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#272 add contrast alpha node
  .changeset/lovely-boxes-knock.md
  packages/graph-editor/src/components/commandPalette/index.tsx
  packages/graph-editor/src/components/panels/dropPanel/data.tsx
  packages/graph-editor/src/components/portPanel/index.tsx
  packages/graph-editor/src/editor/actions/createNode.tsx
  packages/graph-editor/src/editor/actions/handleDrop.tsx
  packages/graph-editor/src/editor/graph.tsx
  packages/graph-engine/src/nodes/color/contrastingAlpha.ts
  packages/graph-engine/src/nodes/color/flattenAlpha.ts
  packages/graph-engine/src/nodes/color/index.ts
  packages/graph-engine/src/nodes/color/lib/flattenAlpha.ts
  packages/graph-engine/src/types.ts
Labels: enhancement, Review effort [1-5]: 4

#278 UI rework
  packages/graph-editor/src/components/flow/handles.tsx
  packages/graph-editor/src/components/flow/wrapper/node.tsx
  packages/graph-editor/src/components/flow/wrapper/nodeV2.tsx
  packages/graph-editor/src/components/menubar/defaults.tsx
  packages/graph-editor/src/constants.ts
  packages/graph-editor/src/css/reactflow.css
  packages/graph-editor/src/editor/layoutController.tsx
  packages/graph-editor/src/redux/models/graph.ts
  packages/graph-editor/src/redux/selectors/graph.ts
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#281 prevent delete when annotation is present
  packages/graph-editor/src/components/contextMenus/nodeContextMenu.tsx
  packages/graph-editor/src/components/hotKeys/index.tsx
  packages/graph-editor/src/hooks/useCanDeleteNode.ts
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#283 add colors to legend
  packages/graph-editor/src/components/commandPalette/index.tsx
  packages/graph-editor/src/css/reactflow.css
  packages/graph-editor/src/editor/layoutController.tsx
  packages/graph-editor/src/index.scss
  packages/graph-editor/src/tokens/colors.ts
  packages/ui/src/styles/styles.scss
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#300 Fix color wheel
  .changeset/mighty-dancers-attack.md
  packages/graph-engine/src/nodes/color/wheel.ts
Labels: enhancement, Bug fix, Review effort [1-5]: 2

#298 fix position reference
  packages/graph-editor/src/editor/actions/duplicate.ts
Labels: Bug fix, Review effort [1-5]: 2

#306 Fix enum array.
  .changeset/thick-moose-wave.md
  .github/workflows/docker-release.yml
  .github/workflows/gimlet.yml
  packages/graph-editor/src/components/flow/wrapper/nodeV2.tsx
  packages/graph-editor/src/components/panels/inputs/dynamicInputs.tsx
  packages/migrations/src/migrations/types.ts
  packages/migrations/src/utils.ts
Labels: enhancement, Review effort [1-5]: 3, Bug fix, Configuration changes

#313 Fix default import
  .changeset/dry-donkeys-cheer.md
  packages/graph-editor/src/registry/inputControls.tsx
Labels: Review effort [1-5]: 1, Bug fix

#315 Add error boundary component
  .changeset/angry-dolls-call.md
  packages/graph-editor/package.json
  packages/graph-editor/src/components/ErrorBoundaryContent.tsx
  packages/graph-editor/src/editor/layoutController.tsx
  packages/graph-editor/src/registry/specifics.tsx
  yarn.lock
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#340 Fix selection
  .changeset/mighty-donuts-wait.md
  packages/graph-editor/src/components/commandPalette/index.tsx
  packages/graph-editor/src/components/flow/wrapper/node.tsx
  packages/graph-editor/src/editor/actions/createNode.tsx
  packages/graph-editor/src/editor/graph.tsx
  packages/graph-editor/src/hooks/useSelectAddedNodes.tsx
  packages/graph-editor/src/hooks/useSetCurrentNode.tsx
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#344 Feat/improve bezier
  .changeset/blue-moons-know.md
  packages/graph-editor/src/components/flow/edges/edge.tsx
  packages/graph-editor/src/components/flow/edges/offsetBezier.ts
  packages/graph-editor/src/components/panels/settings/index.tsx
  packages/graph-editor/src/editor/graph.tsx
  packages/graph-editor/src/redux/models/settings.ts
  packages/graph-editor/src/redux/selectors/settings.ts
  packages/nodes-design-tokens/jest.config.ts
  packages/nodes-design-tokens/src/index.ts
  packages/nodes-design-tokens/src/nodes/advancedBlend.ts
  packages/nodes-design-tokens/src/nodes/arrayToSet.ts
  packages/nodes-design-tokens/src/nodes/create.ts
  packages/nodes-design-tokens/src/nodes/externalTokens.ts
  packages/nodes-design-tokens/src/nodes/extractSingleToken.ts
  packages/nodes-design-tokens/src/nodes/flatten.ts
  packages/nodes-design-tokens/src/nodes/group.ts
  packages/nodes-design-tokens/src/nodes/index.ts
  packages/nodes-design-tokens/src/nodes/inlineTokens.ts
  packages/nodes-design-tokens/src/nodes/invert.ts
  packages/nodes-design-tokens/src/nodes/leonardoColor.ts
  packages/nodes-design-tokens/src/nodes/leonardoTheme.ts
  packages/nodes-design-tokens/src/nodes/name.ts
  packages/nodes-design-tokens/src/nodes/nearest.ts
  packages/nodes-design-tokens/src/nodes/previewTypography.ts
  packages/nodes-design-tokens/src/nodes/resolve.ts
  packages/nodes-design-tokens/src/nodes/setToArray.ts
  packages/nodes-design-tokens/src/nodes/ungroup.ts
  packages/nodes-design-tokens/src/schemas/index.ts
  packages/nodes-design-tokens/src/schemas/utils.ts
  packages/nodes-design-tokens/src/ui/controls/preview/color.tsx
  packages/nodes-design-tokens/src/ui/controls/token.tsx
  packages/nodes-design-tokens/src/ui/controls/tokenSet.tsx
  packages/nodes-design-tokens/src/ui/controls/variadicTokenSet.tsx
  packages/nodes-design-tokens/src/ui/nodes/typography.tsx
  packages/nodes-design-tokens/src/utils/index.ts
  packages/nodes-design-tokens/src/utils/sortTokens.ts
  packages/nodes-design-tokens/tests/sets/resolve.test.ts
  packages/nodes-design-tokens/tsconfig.json
  packages/nodes-design-tokens/tsconfig.prod.json
  packages/nodes-design-tokens/tsconfig.test.json
  packages/nodes-design-tokens/tsup.config.ts
Labels: enhancement, Review effort [1-5]: 3, Bug fix, Tests

#302 fix type on contrasting alpha
  .changeset/short-days-sparkle.md
  packages/graph-engine/src/nodes/color/contrastingAlpha.ts
Labels: documentation, Review effort [1-5]: 1, Bug fix

#350 Fix bugs for node value preview and passthrough node
  packages/graph-editor/src/components/flow/handles.tsx
  packages/graph-editor/src/components/flow/nodes/passthroughNode.tsx
  packages/graph-editor/src/components/flow/wrapper/nodeV2.tsx
  yarn.lock
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#346 fix width swatch in color compare node
  .changeset/wet-peaches-hug.md
  packages/graph-editor/src/components/preview/colorCompare.tsx
Labels: documentation, Review effort [1-5]: 1, Bug fix

#354 Check for common type when setting variadic type
  .changeset/happy-ducks-relax.md
  packages/graph-engine/src/programmatic/input.ts
Labels: enhancement, Review effort [1-5]: 3

#358 Change contrasting alpha type
  .changeset/grumpy-kangaroos-repair.md
  packages/graph-engine/src/nodes/color/contrastingAlpha.ts
Labels: documentation, Bug fix, Review effort [1-5]: 2

#366 fix center alignment on node handles
  .changeset/dull-games-hunt.md
  packages/graph-editor/src/components/flow/handles.tsx
Labels: documentation, Review effort [1-5]: 1, Bug fix

#347 ui desaturation and minimal styles
  packages/graph-editor/src/components/colorPicker/index.tsx
  packages/graph-editor/src/components/commandPalette/index.tsx
  packages/graph-editor/src/components/controls/color.tsx
  packages/graph-editor/src/components/curveEditor/override.css
  packages/graph-editor/src/css/cmdk.css
  packages/graph-editor/src/css/rc-dock.css
  packages/graph-editor/src/css/reactflow.css
  packages/graph-editor/src/index.scss
  packages/graph-engine/src/nodes/accessibility/colorBlindness.ts
  packages/graph-engine/src/nodes/array/arraySubgraph.ts
  packages/graph-engine/src/nodes/array/arrify.ts
  packages/graph-engine/src/nodes/array/indexArray.ts
  packages/graph-engine/src/nodes/array/push.ts
  packages/graph-engine/src/nodes/color/blend.ts
  packages/graph-engine/src/nodes/color/contrast.ts
  packages/graph-engine/src/nodes/color/contrasting.ts
  packages/graph-engine/src/nodes/color/convert.ts
  packages/graph-engine/src/nodes/color/create.ts
  packages/graph-engine/src/nodes/color/distance.ts
  packages/graph-engine/src/nodes/color/flattenAlpha.ts
  packages/graph-engine/src/nodes/color/scale.ts
  packages/graph-engine/src/nodes/typography/baseFontSize.ts
  packages/ui/src/styles/styles.scss
  readme.md
Labels: documentation, enhancement, Review effort [1-5]: 3

#368 Fix/group level icons
  .changeset/good-suns-compare.md
  packages/graph-editor/src/components/commandPalette/index.tsx
  packages/graph-editor/src/components/flow/wrapper/nodeV2.tsx
  packages/graph-editor/src/components/panels/dropPanel/NodeEntry.tsx
  packages/graph-editor/src/components/panels/dropPanel/data.tsx
  packages/graph-editor/src/components/panels/dropPanel/dropPanel.tsx
  packages/graph-editor/src/editor/actions/createNode.tsx
  packages/graph-editor/src/editor/graph.tsx
  packages/nodes-audio/src/ui/index.tsx
  packages/nodes-design-tokens/src/ui/icons/speaker.tsx
  packages/ui/src/components/editor/panelItems.tsx
Labels: enhancement, Review effort [1-5]: 4

#339 feat(269): Add ability to update array inputs
  .changeset/tough-weeks-eat.md
  packages/graph-editor/src/components/colorPicker/InputPopover.tsx
  packages/graph-editor/src/components/colorPicker/index.tsx
  packages/graph-editor/src/components/controls/array.tsx
  packages/graph-editor/src/registry/control.tsx
Labels: enhancement, Review effort [1-5]: 4
