Repository tokens-studio/graph-engine, pull requests merged in 2025-02, with the labels that each got.

#648 Fix graph editor caching issue
  .changeset/two-carpets-kneel.md
  packages/graph-editor/src/editor/layoutController.tsx
Labels: Review effort [1-5]: 2

#652 added arrays to constant node
  .changeset/sweet-lizards-marry.md
  packages/graph-editor/src/components/controls/any.tsx
  packages/graph-engine/src/nodes/generic/constant.ts
Labels: Review effort [1-5]: 3

#654 fixed MMB pan incorrectly selecting nodes and edges
  .changeset/violet-wasps-learn.md
  packages/graph-editor/src/editor/graph.tsx
Labels: Review effort [1-5]: 2

#656 fixed bottom padding on passthrough node
  packages/graph-editor/src/components/flow/handles.module.css
Labels: Review effort [1-5]: 2

#653 use loader in subgraphs
  .changeset/rich-ducks-retire.md
  packages/graph-engine/src/nodes/array/arraySubgraph.ts
  packages/graph-engine/src/nodes/generic/subgraph.ts
  packages/graph-engine/tests/suites/graph/subgraph.test.ts
  packages/graph-engine/tests/suites/nodes/array/arrayMap.test.ts
Labels: Review effort [1-5]: 2

#658 fixed incorrect empty URI error in ExternalSet
  packages/nodes-design-tokens/src/nodes/externalTokens.ts
Labels: Review effort 2/5

#663 add create reference node
  .changeset/breezy-moose-cough.md
  packages/nodes-design-tokens/src/nodes/createReference.ts
  packages/nodes-design-tokens/src/nodes/index.ts
  packages/nodes-design-tokens/tests/createReference.test.ts
Labels: Review effort 2/5

#661 add contrasting from array node
  .changeset/five-spiders-stare.md
  packages/graph-engine/src/nodes/color/contrastingFromArray.ts
  packages/graph-engine/src/nodes/color/index.ts
  packages/graph-engine/tests/suites/nodes/color/contrastingFromArray.test.ts
Labels: Review effort 4/5
