Repository tokens-studio/graph-engine, pull requests merged in 2025-01, with the labels that each got.

#623 fixes context menu bg
  .changeset/brown-donkeys-appear.md
  packages/graph-editor/src/css/contexify.css
  packages/graph-editor/src/css/contextify.css
  packages/graph-editor/src/data/version.ts
  packages/graph-editor/src/index.css
Labels: Review effort [1-5]: 2

#625 remove slide animation
  .changeset/mean-candles-brush.md
  packages/graph-editor/src/editor/layoutController.tsx
Labels: Review effort [1-5]: 1

#627 fix clsx missing in build
  .changeset/heavy-queens-love.md
  packages/documentation/package.json
  packages/graph-editor/package.json
  packages/graph-editor/src/components/contextMenus/nodeContextMenu.tsx
  packages/storybook-lit/src/components/context/index.ts
  packages/storybook-react/src/context/index.tsx
  packages/ui/package.json
  yarn.lock
Labels: Review effort [1-5]: 2

#616 add typography preview
  .changeset/lemon-knives-wink.md
  packages/nodes-previews/src/index.ts
  packages/nodes-previews/src/token/typography/node.ts
  packages/nodes-previews/src/token/typography/panel.module.css
  packages/nodes-previews/src/token/typography/panel.tsx
  packages/nodes-previews/src/token/typography/specific.tsx
Labels: Review effort [1-5]: 4

#614 Token table
  .changeset/yellow-bugs-tickle.md
  packages/nodes-previews/src/index.ts
  packages/nodes-previews/src/token/table/node.ts
  packages/nodes-previews/src/token/table/panel.module.css
  packages/nodes-previews/src/token/table/panel.tsx
  packages/nodes-previews/src/token/table/specific.tsx
Labels: Review effort [1-5]: 4

#615 Preview palette
  .changeset/many-snakes-grin.md
  packages/nodes-previews/src/index.ts
  packages/nodes-previews/src/token/palette/node.ts
  packages/nodes-previews/src/token/palette/panel.module.css
  packages/nodes-previews/src/token/palette/panel.tsx
  packages/nodes-previews/src/token/palette/specific.tsx
Labels: Review effort [1-5]: 4

#635 fixed spelling mistake in `Token set to token array`
  .changeset/tough-scissors-crash.md
  packages/nodes-design-tokens/src/nodes/setToArray.ts
Labels: Review effort [1-5]: 1

#634 Set zoom value in toolbar to tabular
  .changeset/lucky-peaches-roll.md
  packages/graph-editor/src/components/toolbar/dropdowns/zoom.tsx
Labels: Review effort [1-5]: 1

#636 Fixed not being able to drag nodes at same Y position as the toolbar
  .changeset/proud-balloons-remember.md
  packages/graph-editor/src/components/toolbar/toolbar.module.css
  packages/graph-editor/src/editor/graph.tsx
Labels: Review effort [1-5]: 2

#642 fixed edge anchor styling (#639)
  .changeset/dull-buses-press.md
  packages/graph-editor/src/components/flow/nodes/passthroughNode.tsx
Labels: Review effort [1-5]: 2

#644 Fix breaking Id issue from preview feature
  packages/graph-editor/src/data/version.ts
  packages/graph-editor/src/editor/layoutController.tsx
Labels: Review effort [1-5]: 3
