Repository tokens-studio/graph-engine, pull requests merged in 2025-03, with the labels that each got.

#630 Add Vector2 Operations
  .changeset/strange-suits-move.md
  packages/graph-engine/src/nodes/vector2/add.ts
  packages/graph-engine/src/nodes/vector2/dot.ts
  packages/graph-engine/src/nodes/vector2/index.ts
  packages/graph-engine/src/nodes/vector2/length.ts
  packages/graph-engine/src/nodes/vector2/normalize.ts
  packages/graph-engine/src/nodes/vector2/scale.ts
  packages/graph-engine/src/nodes/vector2/subtract.ts
  packages/graph-engine/tests/suites/nodes/vector2/add.test.ts
  packages/graph-engine/tests/suites/nodes/vector2/dot.test.ts
  packages/graph-engine/tests/suites/nodes/vector2/length.test.ts
  packages/graph-engine/tests/suites/nodes/vector2/normalize.test.ts
  packages/graph-engine/tests/suites/nodes/vector2/scale.test.ts
  packages/graph-engine/tests/suites/nodes/vector2/subtract.test.ts
Labels: Review effort [1-5]: 3

#672 fixed variadic input style
  packages/graph-editor/src/components/flow/wrapper/nodeV2.tsx
Labels: Review effort 2/5

#679 fixed Color Blindness node always returning 000
  .changeset/thin-tigers-agree.md
  packages/graph-engine/src/nodes/accessibility/colorBlindness.ts
Labels: Review effort 2/5

#682 Add langfuse
  .changeset/dull-laws-sniff.md
  .gimlet/graph-engine-beta.yaml
  .gimlet/graph-engine.yaml
  packages/graph-editor/src/data/version.ts
  packages/ui/next.config.mjs
  packages/ui/package.json
  packages/ui/src/api/controllers/ai.ts
  packages/ui/src/instrumentation.ts
  packages/ui/src/lib/anthropic/index.ts
  yarn.lock
Labels: Review effort 4/5

#685 renamed Destruct Token to Deconstruct
  .changeset/weak-peas-repair.md
  packages/nodes-design-tokens/src/nodes/destructToken.ts
Labels: Review effort 1/5

#662 added copy/paste to graph editor
  .changeset/stale-countries-refuse.md
  packages/graph-editor/package.json
  packages/graph-editor/src/components/contextMenus/nodeContextMenu.tsx
  packages/graph-editor/src/components/contextMenus/paneContextMenu.tsx
  packages/graph-editor/src/components/contextMenus/selectionContextMenu.tsx
  packages/graph-editor/src/components/hotKeys/index.tsx
  packages/graph-editor/src/components/hotKeys/utils.ts
  packages/graph-editor/src/editor/actions/deleteSelectedNodes.tsx
  packages/graph-editor/src/editor/graph.tsx
  packages/graph-editor/src/hooks/useCopyPaste.ts
  packages/graph-editor/src/tests/useCopyPaste.test.tsx
  packages/graph-editor/src/utils/pluralizeValue.ts
  packages/graph-editor/vitest.config.ts
Labels: Review effort 4/5
